### ISSUE TITLE
About salt vs ansible topic

### ISSUE THREAD

**Issue by liuzheng712** [JensRantil/jensrantil.github.io#4]
from ansible import playbook, callbacks
    def run_playbook(playbook_path, hosts_path):
        stats = callbacks.AggregateStats()
        playbook_cb = callbacks.PlaybookCallbacks(verbose=0)
        runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=0)
        playbook.PlayBook(
            playbook=playbook_path,
            host_list=hosts_path,
            stats=stats,
            forks=4,
            callbacks=playbook_cb,
            runner_callbacks=runner_cb,
        ).run()
    if __name__ == '__main__':
        stats = run_playbook(
            playbook_path='/tmp/playbook',
            hosts_path='/tmp/hosts',
            )
        print stats

**Comment by JensRantil** [comment]
I'll be closing this as I've responded to you as per e-mail.
